-- MySQL Script generated by MySQL Workbench
-- Thu Jul 13 09:42:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_OS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_OS` ;

-- -----------------------------------------------------
-- Schema BD_OS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_OS` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `BD_OS` ;

-- -----------------------------------------------------
-- Table `Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Login` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Login` (
  `Log_id` INT NOT NULL AUTO_INCREMENT,
  `Log_nome` VARCHAR(100) NOT NULL,
  `Log_login` VARCHAR(45) NOT NULL,
  `Log_senha` VARCHAR(45) NOT NULL,
  `Log_permissao` INT NOT NULL DEFAULT 0,
  `Log_estatus` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Log_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cid_cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cid_cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cid_cidade` (
  `Cid_id` INT NOT NULL AUTO_INCREMENT,
  `Cid_sigla` VARCHAR(45) NOT NULL,
  `Cid_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cid_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Br_Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Br_Bairro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Br_Bairro` (
  `Br_id` INT NOT NULL AUTO_INCREMENT,
  `Br_sigla` VARCHAR(5) NOT NULL,
  `Br_nome` VARCHAR(45) NOT NULL,
  `Cid_cidade_Cid_id` INT NOT NULL,
  PRIMARY KEY (`Br_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cli_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cli_Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cli_Cliente` (
  `Cli_id` INT NOT NULL AUTO_INCREMENT,
  `Cli_nome` VARCHAR(100) NOT NULL,
  `Cli_sobrenome` VARCHAR(100) NOT NULL,
  `Cli_email` VARCHAR(100) NOT NULL,
  `Cli_endereco` VARCHAR(45) NULL,
  `Cli_complemento` VARCHAR(45) NULL,
  `Cli_telefone` VARCHAR(45) NOT NULL,
  `Cid_cidade_Cid_id` INT NOT NULL,
  `Br_Bairro_Br_id` INT NOT NULL,
  PRIMARY KEY (`Cli_id`, `Cid_cidade_Cid_id`, `Br_Bairro_Br_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Maq_maquina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Maq_maquina` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Maq_maquina` (
  `Maq_id` INT NOT NULL AUTO_INCREMENT,
  `Maq_nome` VARCHAR(45) NOT NULL,
  `Maq_data` DATETIME NOT NULL,
  `Maq_processador` VARCHAR(45) NOT NULL,
  `Maq_placamae` VARCHAR(45) NOT NULL,
  `Maq_memoria` VARCHAR(45) NOT NULL,
  `Maq_qtmemoria` VARCHAR(45) NOT NULL,
  `Maq_hd` VARCHAR(45) NOT NULL,
  `Maq_qthd` VARCHAR(45) NOT NULL,
  `Maq_sistemaop` VARCHAR(45) NOT NULL,
  `Maq_fonte` VARCHAR(45) NOT NULL,
  `Maq_potenciafonte` VARCHAR(45) NOT NULL,
  `Maq_vga` VARCHAR(45) NULL,
  `Cli_Cliente_Cli_id` INT NOT NULL,
  PRIMARY KEY (`Maq_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `For_fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `For_fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `For_fornecedor` (
  `For_id` INT NOT NULL AUTO_INCREMENT,
  `For_nome` VARCHAR(45) NOT NULL,
  `For_email` VARCHAR(45) NOT NULL,
  `For_telefone` VARCHAR(45) NOT NULL,
  `For_endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`For_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Mar_marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Mar_marca` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Mar_marca` (
  `Mar_id` INT NOT NULL AUTO_INCREMENT,
  `Mar_sigla` VARCHAR(45) NOT NULL,
  `Mar_nome` VARCHAR(45) NOT NULL,
  `For_fornecedor_For_id` INT NOT NULL,
  PRIMARY KEY (`Mar_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Eq_Equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eq_Equipamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Eq_Equipamento` (
  `Eq_id` INT NOT NULL AUTO_INCREMENT,
  `Eq_sigla` VARCHAR(45) NOT NULL,
  `Eq_nome` VARCHAR(45) NOT NULL,
  `Mar_marca_Mar_id` INT NOT NULL,
  PRIMARY KEY (`Eq_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Os_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Os_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Os_os` (
  `Os_id` INT NOT NULL AUTO_INCREMENT,
  `Os_data` DATETIME NOT NULL,
  `Os_motivo` VARCHAR(300) NOT NULL,
  `Os_dataini` DATETIME NULL,
  `Os_datafim` DATETIME NULL,
  `Os_trocaequip` VARCHAR(1) NOT NULL DEFAULT 'N',
  `Os_Valor` VARCHAR(45) NOT NULL,
  `Maq_maquina_Maq_id` INT NOT NULL,
  `Eq_Equipamento_Eq_id` INT NOT NULL,
  `Login_Log_id` INT NOT NULL,
  PRIMARY KEY (`Os_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
